<a href="https://colab.research.google.com/github/kalidindi-harshitha/NASSCOM/blob/main/WEEK%202/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")


--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------


In [2]:
# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

arr1_1 = np.arange(100)
arr1_2 = np.ones((3, 3))
arr1_3 = np.full((2, 4), 7)
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])



--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[30 40 44 18 16]
 [16 16 46 42 30]]


In [3]:
print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

val2_1 = data[2, 3]
row2_2 = data[0]
col2_3 = data[:, -1]
sub_arr2_4 = data[1:3, 0:2]
filtered_elements2_5 = data[data > 100]

print("val2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)


--- Task 2: Indexing and Slicing with Arrays ---
val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]


In [4]:
print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))

arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)
even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("arr3_1:\n", arr3_1)
print("arr3_2:\n", arr3_2)
print("even_count3_3:", even_count3_3)


--- Task 3: Conditional Operations ---
arr3_1:
 [[12  1 19 18 11]
 [15 18  5 12 12]
 [ 6  9 13 11 14]
 [10  1  7  5  2]]
arr3_2:
 [[12  0 19 18 11]
 [15 18  0 12 12]
 [ 0  0 13 11 14]
 [10  0  0  0  0]]
even_count3_3: 9


In [5]:
print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

sum4_1 = np.sum(arr4_1)
mean_cols4_2 = np.mean(arr4_1, axis=0)
max_rows4_3 = np.max(arr4_1, axis=1)
std4_4 = np.std(arr4_1)

print("sum4_1:", sum4_1)
print("mean_cols4_2:", mean_cols4_2)
print("max_rows4_3:", max_rows4_3)
print("std4_4:", std4_4)




--- Task 4: Aggregation Functions ---
sum4_1: 84
mean_cols4_2: [11.          6.66666667 10.33333333]
max_rows4_3: [12 15 20]
std4_4: 5.2493385826745405


In [6]:
print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)

reshaped_arr5_2 = arr5_1.reshape(4, 6)
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)
flattened_arr5_4 = reshaped_arr5_2.flatten()

# Using ravel() also
ravelled_arr5_4 = reshaped_arr5_2.ravel()

print("reshaped_arr5_2:\n", reshaped_arr5_2)
print("reshaped_arr5_3:\n", reshaped_arr5_3)
print("flattened_arr5_4:", flattened_arr5_4)
print("ravelled_arr5_4:", ravelled_arr5_4)



--- Task 5: Reshaping and Flattening ---
reshaped_arr5_2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
reshaped_arr5_3:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
flattened_arr5_4: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
ravelled_arr5_4: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [7]:
print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])

result6_1 = arr6_1 + scalar
result6_2 = arr6_1 + vector

print("result6_1:\n", result6_1)
print("result6_2:\n", result6_2)


--- Task 6: Broadcasting ---
result6_1:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
result6_2:
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [8]:
print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

# View
view_arr7 = original_arr7[:]
view_arr7[0] = 99

print("view_arr7:", view_arr7)
print("original_arr7 after modifying view:", original_arr7)

# Copy
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("copy_arr7:", copy_arr7)
print("original_arr7 after modifying copy:", original_arr7)




--- Task 7: Copying vs. Viewing Arrays ---
view_arr7: [99  2  3  4  5]
original_arr7 after modifying view: [99  2  3  4  5]
copy_arr7: [99  2  3  4  0]
original_arr7 after modifying copy: [99  2  3  4  5]


In [12]:
print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

vstack_arr8_1 = np.vstack((arr8_a, arr8_b))
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# Split into 3 parts
part1, part2, part3 = np.vsplit(combined_arr8_3, [2, 4])

print("vstack_arr8_1:\n", vstack_arr8_1)
print("hstack_arr8_2:\n", hstack_arr8_2)
print("combined_arr8_3:\n", combined_arr8_3)
print("part1:\n", part1)
print("part2:\n", part2)
print("part3:\n", part3)


--- Task 8: Stacking and Splitting Arrays ---
vstack_arr8_1:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack_arr8_2:
 [[1 2 5 6]
 [3 4 7 8]]
combined_arr8_3:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
part1:
 [[1 2]
 [3 4]]
part2:
 [[5 6]
 [7 8]]
part3:
 [[ 9 10]]


In [10]:
print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])

arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

sorted_arr9_1 = np.sort(arr9_1)

# axis=0 means sorting each column independently
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

idx9_3 = np.where(arr9_1 == 9)
max_idx9_4 = np.argmax(arr9_1)

print("sorted_arr9_1:", sorted_arr9_1)
print("sorted_cols9_2:\n", sorted_cols9_2)
print("idx9_3:", idx9_3)
print("max_idx9_4:", max_idx9_4)


--- Task 9: Sorting and Searching ---
sorted_arr9_1: [1 2 3 4 5 6 7 8 9]
sorted_cols9_2:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]
idx9_3: (array([4]),)
max_idx9_4: 4
