<a href="https://colab.research.google.com/github/kalidindi-harshitha/NASSCOM/blob/main/WEEK%202/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")



--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------


In [2]:
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array with random integers between 1 and 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert NumPy array into DataFrame
df1_3 = pd.DataFrame(
    np_array1_2,
    columns=['A', 'B', 'C', 'D']
)

print("\nSeries:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame:")
print(df1_3)


--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---

Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[51 68 47 41]
 [58 74 26 33]
 [64 37 94 71]]

DataFrame:
    A   B   C   D
0  51  68  47  41
1  58  74  26  33
2  64  37  94  71


In [3]:
print("\n--- Task 2: Synthetic Data Generation for Practice ---")

# Create DataFrame with 100 rows
df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', end='2023-04-10', periods=100),
    'Region': np.random.choice(
        ['East', 'West', 'North', 'South'],
        size=100
    ),
    'Product': np.random.choice(
        ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
        size=100
    ),
    'Sales': np.random.randint(100, 1001, size=100),
    'Quantity': np.random.randint(1, 11, size=100)
})

# Introduce NaN values
sales_nan_indices = np.random.choice(df_sales.index, size=5, replace=False)
quantity_nan_indices = np.random.choice(df_sales.index, size=3, replace=False)

df_sales.loc[sales_nan_indices, 'Sales'] = np.nan
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan

print("\nSales DataFrame:")
print(df_sales)



--- Task 2: Synthetic Data Generation for Practice ---

Sales DataFrame:
         Date Region   Product  Sales  Quantity
0  2023-01-01   West   Monitor  972.0       8.0
1  2023-01-02   East     Mouse  630.0       6.0
2  2023-01-03  South    Laptop  777.0       5.0
3  2023-01-04   West     Mouse  672.0       4.0
4  2023-01-05  South   Monitor  346.0       6.0
..        ...    ...       ...    ...       ...
95 2023-04-06   West  Keyboard  160.0      10.0
96 2023-04-07   West  Keyboard  633.0       2.0
97 2023-04-08  South    Laptop  998.0       2.0
98 2023-04-09   East  Keyboard  675.0       3.0
99 2023-04-10  South   Monitor  906.0       7.0

[100 rows x 5 columns]


In [4]:
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# 3.1 Select Region and Sales columns
df3_1 = df_sales[['Region', 'Sales']]

# 3.2 Select rows where Product is Laptop
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

# 3.3 Region is East AND Sales > 500
df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

# 3.4 Select Sales value for first entry where Product is Monitor
monitor_rows = df_sales[df_sales['Product'] == 'Monitor']

if not monitor_rows.empty:
    val3_4 = df_sales.loc[monitor_rows.index[0], 'Sales']
    val3_4 = monitor_rows.iloc[0]['Sales']
else:
    val3_4 = np.nan

print("\nTask 3.1:")
print(df3_1)

print("\nTask 3.2:")
print(df3_2)

print("\nTask 3.3:")
print(df3_3)

print("\nTask 3.4:")
print(val3_4)


--- Task 3: Indexing and Slicing in DataFrames ---

Task 3.1:
   Region  Sales
0    West  972.0
1    East  630.0
2   South  777.0
3    West  672.0
4   South  346.0
..    ...    ...
95   West  160.0
96   West  633.0
97  South  998.0
98   East  675.0
99  South  906.0

[100 rows x 2 columns]

Task 3.2:
         Date Region Product  Sales  Quantity
2  2023-01-03  South  Laptop  777.0       5.0
10 2023-01-11   West  Laptop  437.0       1.0
13 2023-01-14  South  Laptop  800.0       8.0
14 2023-01-15   West  Laptop  266.0       8.0
19 2023-01-20  North  Laptop  587.0       3.0
26 2023-01-27   West  Laptop  486.0       8.0
28 2023-01-29   East  Laptop  317.0       2.0
33 2023-02-03  North  Laptop  672.0       6.0
34 2023-02-04  South  Laptop  971.0       7.0
36 2023-02-06  North  Laptop  217.0       4.0
38 2023-02-08   West  Laptop  215.0       1.0
47 2023-02-17  North  Laptop  126.0       7.0
49 2023-02-19   West  Laptop  357.0       NaN
50 2023-02-20   East  Laptop  497.0       3.0
52 2023-

In [5]:
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

# 4.1 Check missing values in each column
missing_counts4_1 = df_sales.isna().sum()

# 4.2 Fill missing Sales values with mean
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(
    df4_2_filled['Sales'].mean()
)

# 4.3 Drop rows having any missing values
df4_3_dropped = df_sales.dropna()

print("\nMissing values:")
print(missing_counts4_1)

print("\nDataFrame after filling Sales:")
print(df4_2_filled)

print("\nDataFrame after dropping rows with NaN:")
print(df4_3_dropped)



--- Task 4: Data Cleaning (Handling Missing Values) ---

Missing values:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

DataFrame after filling Sales:
         Date Region   Product  Sales  Quantity
0  2023-01-01   West   Monitor  972.0       8.0
1  2023-01-02   East     Mouse  630.0       6.0
2  2023-01-03  South    Laptop  777.0       5.0
3  2023-01-04   West     Mouse  672.0       4.0
4  2023-01-05  South   Monitor  346.0       6.0
..        ...    ...       ...    ...       ...
95 2023-04-06   West  Keyboard  160.0      10.0
96 2023-04-07   West  Keyboard  633.0       2.0
97 2023-04-08  South    Laptop  998.0       2.0
98 2023-04-09   East  Keyboard  675.0       3.0
99 2023-04-10  South   Monitor  906.0       7.0

[100 rows x 5 columns]

DataFrame after dropping rows with NaN:
         Date Region   Product  Sales  Quantity
0  2023-01-01   West   Monitor  972.0       8.0
1  2023-01-02   East     Mouse  630.0       6.0
2  2023-01-03  South    La

In [6]:
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# 5.1 Create Total_Revenue column
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

# 5.2 Sort by Date ascending and Sales descending
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

# 5.3 Group by Region and calculate sum of Sales and Quantity
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

# 5.4 Group by Product and calculate average Sales
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("\nTask 5.1:")
print(df_sales)

print("\nTask 5.2:")
print(df5_2_sorted)

print("\nTask 5.3:")
print(df5_3_grouped_region)

print("\nTask 5.4:")
print(df5_4_grouped_product)


--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---

Task 5.1:
         Date Region   Product  Sales  Quantity  Total_Revenue
0  2023-01-01   West   Monitor  972.0       8.0         7776.0
1  2023-01-02   East     Mouse  630.0       6.0         3780.0
2  2023-01-03  South    Laptop  777.0       5.0         3885.0
3  2023-01-04   West     Mouse  672.0       4.0         2688.0
4  2023-01-05  South   Monitor  346.0       6.0         2076.0
..        ...    ...       ...    ...       ...            ...
95 2023-04-06   West  Keyboard  160.0      10.0         1600.0
96 2023-04-07   West  Keyboard  633.0       2.0         1266.0
97 2023-04-08  South    Laptop  998.0       2.0         1996.0
98 2023-04-09   East  Keyboard  675.0       3.0         2025.0
99 2023-04-10  South   Monitor  906.0       7.0         6342.0

[100 rows x 6 columns]

Task 5.2:
         Date Region   Product  Sales  Quantity  Total_Revenue
0  2023-01-01   West   Monitor  972.0       8.0         7776.0
1  2023-